KL-589 Fop shipment sender may pay shipment cost by non-cash
vokilam-d/tCommerce-backend pull request #56
Opened 2021-07-25 19:17 UTC by malikov-yurii

2021-07-25 20:06 UTC, vokilam-d requested changes

2021-07-25 20:06 UTC, vokilam-d commented on src/nova-poshta/nova-poshta.service.ts
> +    let shipmentPaymentMethod = NovaPoshtaService.getShipmentPaymentMethod(sender, shipment);
может здесь лучше ошибку кинуть, если кто-то пытается установить NON_CACHE для не фопа и не SENDER?
вместо того, чтоб программно менять выбранное значение.

а то получается человек может выбрать нон-кеш, и отправителя не фопа, а ему успешно создастся накладная, а человек даже не узнает, что метод оплаты поменялся

как считаешь

2021-07-25 20:47 UTC, malikov-yurii commented
tested. Can merge

2021-07-26 06:36 UTC, malikov-yurii commented on src/nova-poshta/nova-poshta.service.ts
> +    let shipmentPaymentMethod = NovaPoshtaService.getShipmentPaymentMethod(sender, shipment);
Согласен, лучше ошибку. Можно пока так смёржить, а потом доделать. Особенно в свете того, что пока на юай нет выбора способа оплаты :)

2021-07-26 08:15 UTC, vokilam-d approved these changes

2021-07-26 08:15 UTC, merged

2021-07-26 08:16 UTC, vokilam-d commented
$patch