KL-609 Discounted prices by purchase amount
vokilam-d/tCommerce-backend pull request #65
Opened 2021-08-26 06:48 UTC by malikov-yurii

2021-08-28 21:24 UTC, malikov-yurii commented
@vokilam-d @ljimmyl Уже можно ревьюить, но мёржить ток с клиентской часть вместе можно

2021-08-29 11:32 UTC, vokilam-d requested changes

2021-08-29 11:32 UTC, vokilam-d commented on src/customer/customer.service.ts
> +    const customer = await this.customerModel.findById(customerId);
здесь тоже нужно сессию добавить
```typescript
...findById(...).session(session).exec();
```

2021-08-29 11:32 UTC, vokilam-d commented on src/discount/services/discount.service.ts
> +}) ();
чот тут оверинжиринг немношк)
- или помести функцию внутрь класса и вызови на старте приложения, посмотри `onApplicationBootstrap()`
- или вызови `initializer();` , можно её тогда в другой файл куда-то

бо неочевидный код получается

1-ый вариант мне больше нра канеш, можно тогда и константы как статик приват поля класса сделать, они ж нигде больше не используются.

у меня плохо было сделано, не делай как у меня )

2021-08-29 11:32 UTC, vokilam-d commented on src/discount/services/discount.service.ts
> +      discountedPrices.push({ costBreakpoint: costBreakpoint, price: Math.round(price * discountFactor) }));
не пиши без фигурных скобок плз, неочевидный код тоже получается, и везде в проекте они есть
```typescript
DISCOUNT_FACTORS_BY_COST_BREAKPOINT.forEach((discountFactor, costBreakpoint) => {
      discountedPrices.push({ costBreakpoint: costBreakpoint, price: Math.round(price * discountFactor) });
});

```

2021-08-29 11:32 UTC, vokilam-d commented on src/discount/services/discount.service.ts
> +const COST_BREAKPOINTS = [] as number[];
тип объявляется после двоеточия, с ним и не надо будет писать `as`:
```typescript
const COST_BREAKPOINTS: number[] = [];
```

 бо `as` это это не объявление типа, а скоре силовое приведение к нему для компилятора:

2021-08-29 11:32 UTC, vokilam-d commented on src/shared/dtos/client/customer.dto.ts
> +  discountCostBreakpoint: number;
а для чего клиенту у кастомера эта инфа?

2021-08-29 11:32 UTC, vokilam-d commented on src/shared/dtos/client/discounted-price.dto.ts
> +export class DiscountedPriceDto {
все клиентские дто помечай плз префиксом `Client`, а то потом тяжело будет разобраться

2021-08-29 11:32 UTC, vokilam-d commented on src/shared/dtos/client/price.dto.ts
> +export class PriceDto {
тут наверное лучше будет явно сказать, что это Product price ? бо уже есть `ClientOrderPricesDto`. может тоже самое и для `DiscountedPriceDto` сказать?

все клиентские дто помечай плз префиксом `Client`, а то потом тяжело будет разобраться

2021-08-30 08:03 UTC, malikov-yurii commented
@vokilam-d  пока не трать время на ревью :) Эта ветка в драфте и чисто для Насти чтобы можно было клиентскую часть начать делать

2021-09-24 06:23 UTC, malikov-yurii commented on src/customer/customer.service.ts
> +    const customer = await this.customerModel.findById(customerId);
Танки!

2021-09-24 06:23 UTC, malikov-yurii commented on src/discount/services/discount.service.ts
> +}) ();
я сделаль)

2021-09-24 06:25 UTC, malikov-yurii commented on src/discount/services/discount.service.ts
> +      discountedPrices.push({ costBreakpoint: costBreakpoint, price: Math.round(price * discountFactor) }));
а вот это интересно. В ждаве такая лямбда пишется без скобок и не встречал кодстайла, где требуются скобки. Как по мне читаемость не страдает. Но аргумент, что везде так в проекте - это согласен. Сделал :)

2021-09-24 06:25 UTC, malikov-yurii commented on src/shared/dtos/client/customer.dto.ts
> +  discountCostBreakpoint: number;
уже нет этого

2021-09-24 06:25 UTC, malikov-yurii commented on src/shared/dtos/client/discounted-price.dto.ts
> +export class DiscountedPriceDto {
Сделал

2021-09-24 06:31 UTC, malikov-yurii commented on src/discount/services/discount.service.ts
> +  public static toClientDiscountedPrices(discountedPrices: AdminProductDiscountedPriceDto[]): ClientProductDiscountedPriceDto[] {
по идее такой метод должен быть либо в отдельном маппер классе или фабрике. Или чуть похуже, но терпимо: в методе AdminProductDiscountedPriceDto.toClientProductDiscountedPriceDto.. Последнее не оч нра + тут есть логика таки небольшая (price ассайнится из priceInDefaultCurrency). Хз шо лучше. Поэтому оставил тут пока

2021-09-24 19:25 UTC, vokilam-d commented on src/product/services/admin-product.service.ts
> +  async updateAllProductDiscountedPrices() {
це шось типо тестове, хай временно буде, пока не смерджим? или как

2021-09-25 07:14 UTC, malikov-yurii commented on src/product/services/admin-product.service.ts
> +  async updateAllProductDiscountedPrices() {
да, так и есть. Это когда сейчас стейджинг продом обновляю, то запускаю и после деплоя в прод нужно будет заранить разец

2021-09-26 15:23 UTC, vokilam-d commented on src/discount/services/discount.service.ts
> +  public static toClientDiscountedPrices(discountedPrices: AdminProductDiscountedPriceDto[]): ClientProductDiscountedPriceDto[] {
@malikov-yurii мне кажется можно перенести в статический метод в класс `ClientProductDiscountedPriceDto`, бо `priceInDefaultCurrency`->`price` это ж и есть по сути маппинг

и я уже такое же делал для почти всех клиентских дто, напр. у `ClientMetaTagsDto`, `ClientCustomerDto` и т.д. есть метод `transformToDto`

2021-09-26 18:41 UTC, vokilam-d approved these changes

2021-09-26 18:41 UTC, merged

2021-09-26 18:41 UTC, vokilam-d commented
$minor