KL-611 Send sms on order placed by customer
vokilam-d/tCommerce-backend pull request #69
Opened 2021-09-21 09:34 UTC by malikov-yurii

2021-09-21 09:41 UTC, malikov-yurii commented
По факту можно мержить бекенд до имплементации части админки. В бекенде я пока добавил, чтобы в админке ордер вью была инфа по смс, чтобы можно было показать на странице заказа. Потом добавлю бекенд, чтобы можно было показать смс на странице клиента. И ещё бекенд эндпоинт сделаю потом, чтобы можно было отправлять человеку смс со страницы заказа и страницы клиента. И ещё потом уже другого типа смс добавим (когда посылка отправлена и на фискализацию чтобы ссылка была на сайт налоговой на чек)

2021-09-21 11:38 UTC, vokilam-d requested changes

2021-09-21 11:38 UTC, vokilam-d commented on src/sms/services/sms.service.ts
> +        throw new NotFoundException(__('Product with id "$1" not found', adminDefaultLanguage, id));
`Product` слово недопоменял

2021-09-21 11:38 UTC, vokilam-d commented on src/sms/services/sms.service.ts
> +      this.scheduleMsgStatusVerification(createdSms, 5000, 5);
может эти магические числа (`5000`, `10_000`, `60_000`) вынести в поля класса?
статик например

2021-09-21 11:38 UTC, vokilam-d commented on src/sms/services/sms.service.ts
> +  private async scheduleMsgStatusVerification(sms: Sms, delayMillis: number, attempts: number) {
`attempts` никак не используется

2021-09-23 07:35 UTC, malikov-yurii commented on src/sms/services/sms.service.ts
> +        throw new NotFoundException(__('Product with id "$1" not found', adminDefaultLanguage, id));
спасибо, поменял

2021-09-23 07:35 UTC, malikov-yurii commented on src/sms/services/sms.service.ts
> +      this.scheduleMsgStatusVerification(createdSms, 5000, 5);
сделал

2021-09-23 07:35 UTC, malikov-yurii commented on src/sms/services/sms.service.ts
> +  private async scheduleMsgStatusVerification(sms: Sms, delayMillis: number, attempts: number) {
ух, жесть. исправил

2021-09-23 07:36 UTC, malikov-yurii commented
@vokilam-d вроде всё как говорили сделал

2021-09-23 09:02 UTC, vokilam-d requested changes

2021-09-23 09:02 UTC, vokilam-d commented on src/sms/services/sms.service.ts
> +      return await found.save({ session });
немного перепутал порядок, сначала надо сейвить, а потом коммитить транзакцию, как у тебя в `createSms`, а то оно уже без транзакции по идее будет сохранять

2021-09-23 09:12 UTC, malikov-yurii commented on src/sms/services/sms.service.ts
> +      return await found.save({ session });
ухх, спасибо, исправил

2021-09-23 09:23 UTC, vokilam-d approved these changes

2021-09-23 09:23 UTC, merged

2021-09-23 09:23 UTC, vokilam-d commented
$minor